# Generated by Django 3.0.8 on 2020-07-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('expertise', models.CharField(max_length=50)),
                ('story', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('performed_by', models.ManyToManyField(to='beauty.Technician')),
            ],
        ),
    ]
