# Generated by Django 3.0.8 on 2020-08-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='some string', upload_to='photos/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='technician',
            name='image',
            field=models.ImageField(default='some string', upload_to='photos/%y/%m/%d'),
        ),
    ]
